### ISSUE TITLE
[Bug] every time i kill a mob using a spell and i have soul phylactery equipped my game crashes

### ISSUE THREAD

**Issue by ruan128** [WinDanesz/RiseOfTheAnimagus#19]
### Description

here is a crash report:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 12/13/22 10:46 PM
Description: Ticking player

java.lang.NoClassDefFoundError: baubles/api/BaubleType
	at com.windanesz.wizardryutils.integration.baubles.BaublesIntegration.getEquippedArtefactStacks(BaublesIntegration.java:123)
	at com.windanesz.morphspellpack.handler.EventHandler.onLivingDeathEvent(EventHandler.java:80)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_239_EventHandler_onLivingDeathEvent_LivingDeathEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:615)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1168)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1023)
	at electroblob.wizardry.util.EntityUtils.attackEntityWithoutKnockback(EntityUtils.java:301)
	at electroblob.wizardry.spell.CelestialSmite.onBlockHit(CelestialSmite.java:43)
	at electroblob.wizardry.spell.SpellRay.shootSpell(SpellRay.java:283)
	at electroblob.wizardry.spell.SpellRay.cast(SpellRay.java:168)
	at electroblob.wizardry.item.ItemWand.cast(ItemWand.java:478)
	at electroblob.wizardry.item.ItemWand.onUsingTick(ItemWand.java:442)
	at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2678)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2097)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: baubles.api.BaubleType
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.windanesz.wizardryutils.integration.baubles.BaublesIntegration.getEquippedArtefactStacks(BaublesIntegration.java:123)
	at com.windanesz.morphspellpack.handler.EventHandler.onLivingDeathEvent(EventHandler.java:80)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_239_EventHandler_onLivingDeathEvent_LivingDeathEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:615)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1168)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1023)
	at electroblob.wizardry.util.EntityUtils.attackEntityWithoutKnockback(EntityUtils.java:301)
	at electroblob.wizardry.spell.CelestialSmite.onBlockHit(CelestialSmite.java:43)
	at electroblob.wizardry.spell.SpellRay.shootSpell(SpellRay.java:283)
	at electroblob.wizardry.spell.SpellRay.cast(SpellRay.java:168)
	at electroblob.wizardry.item.ItemWand.cast(ItemWand.java:478)
	at electroblob.wizardry.item.ItemWand.onUsingTick(ItemWand.java:442)
	at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2678)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2097)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 100
	Entity Name: Ruanruan58
	Entity's Exact location: 1568.65, 6.86, -742.59
	Entity's Block location: World: (1568,6,-743), Chunk: (at 0,0,9 in 98,-47; contains blocks 1568,0,-752 to 1583,255,-737), Region: (3,-2; contains chunks 96,-64 to 127,-33, blocks 1536,0,-1024 to 2047,255,-513)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@53112f63
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 528606656 bytes (504 MB) / 838860800 bytes (800 MB) up to 3154116608 bytes (3008 MB)
	JVM Flags: 7 total; -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                          | Signature                                |
	|:------ |:-------------- |:------------ |:------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                   | None                                     |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                   | None                                     |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2859.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge          | 14.23.5.2859 | forge-1.12.2-14.23.5.2859.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ebwizardry     | 4.3.7        | ElectroblobsWizardry-4.3.8.jar  | None                                     |
	| LCHIJA | ichunutil      | 7.2.2        | iChunUtil-1.12.2-7.2.2.jar      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | morph          | 7.2.0        | Morph-1.12.2-7.2.1.jar          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | wizardryutils  | 1.12.2-1.1.3 | WizardryUtils-1.12.2-1.1.3.jar  | None                                     |
	| LCHIJA | morphspellpack | 1.12.2-1.0.0 | MorphSpellPack-1.12.2-1.0.0.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Ruanruan58'/100, l='1.12.2', x=1568.65, y=6.86, z=-742.59]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ruan128** [comment]
all i have done is literally kill mob with a spell while having the soul phylactery also tested with 2 different spells and mobs

**Comment by WinDanesz** [comment]
Download the Baubles mod

**Comment by ruan128** [comment]
> Download the Baubles mod

uh ok

**Comment by ruan128** [comment]
ok it did not crash this time sorry for wasting your time
