### ISSUE TITLE
Game crashes when you stay in morph too long

### ISSUE THREAD

**Issue by IronSasquatch33** [WinDanesz/RiseOfTheAnimagus#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

I used the skinchanger spell to turn into a chicken and then used 10 spell scrolls to extend the time in morph and when I exited the morph the game crashed with an index out of bounds error.
I used one of the stones to turn into a wolf and adjusted the time for five minutes and that also crashed the game. here is the crash report.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 11/8/22 3:41 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at me.ichun.mods.morph.client.model.ModelMorph.updateModelList(ModelMorph.java:274)
	at me.ichun.mods.morph.client.render.RenderPlayerHand.func_177139_c(RenderPlayerHand.java:398)
	at net.minecraft.client.renderer.ItemRenderer.func_187456_a(ItemRenderer.java:259)
	at net.minecraft.client.renderer.ItemRenderer.func_187457_a(ItemRenderer.java:358)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:333)
	at me.ichun.mods.morph.client.core.EventHandlerClient.onRenderHand(EventHandlerClient.java:797)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_977_EventHandlerClient_onRenderHand_RenderHandEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:201)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:772)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1439)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at me.ichun.mods.morph.client.model.ModelMorph.updateModelList(ModelMorph.java:274)
	at me.ichun.mods.morph.client.render.RenderPlayerHand.func_177139_c(RenderPlayerHand.java:398)
	at net.minecraft.client.renderer.ItemRenderer.func_187456_a(ItemRenderer.java:259)
	at net.minecraft.client.renderer.ItemRenderer.func_187457_a(ItemRenderer.java:358)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:333)
	at me.ichun.mods.morph.client.core.EventHandlerClient.onRenderHand(EventHandlerClient.java:797)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_977_EventHandlerClient_onRenderHand_RenderHandEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:201)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:772)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1439)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['IronSasquatch33'/220, l='MpServer', x=52.38, y=74.00, z=1560.50]]
	Chunk stats: MultiplayerChunkCache: 3025, 3025
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,88,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1401596 game time, 126139 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 60 total; [EntitySkeleton['Skeleton'/351489, l='MpServer', x=37.03, y=63.00, z=1497.11], EntitySpider['Spider'/499222, l='MpServer', x=-14.50, y=63.00, z=1506.50], EntityCreeper['Creeper'/499221, l='MpServer', x=-11.50, y=63.00, z=1508.50], EntityPainting['Painting'/603, l='MpServer', x=130.97, y=70.50, z=1627.50], EntityPainting['Painting'/604, l='MpServer', x=130.97, y=70.50, z=1624.50], EntityPainting['Painting'/605, l='MpServer', x=128.97, y=70.50, z=1587.50], EntityPainting['Painting'/606, l='MpServer', x=128.00, y=70.00, z=1596.97], EntityPainting['Painting'/607, l='MpServer', x=128.97, y=70.00, z=1595.00], EntityPainting['Painting'/649, l='MpServer', x=149.97, y=69.50, z=1575.50], EntityPainting['Painting'/650, l='MpServer', x=153.03, y=70.50, z=1573.50], EntityPainting['Painting'/651, l='MpServer', x=157.03, y=69.50, z=1573.50], EntityPainting['Painting'/648, l='MpServer', x=146.03, y=73.50, z=1608.50], EntityPainting['Painting'/555, l='MpServer', x=125.50, y=69.50, z=1623.03], EntityChicken['Chicken'/322, l='MpServer', x=21.69, y=68.00, z=1553.14], EntityVoidCreeper['Void Creeper'/443743, l='MpServer', x=21.34, y=63.00, z=1500.64], EntityPainting['Painting'/603, l='MpServer', x=130.97, y=70.50, z=1627.50], EntityPainting['Painting'/604, l='MpServer', x=130.97, y=70.50, z=1624.50], EntityPainting['Painting'/605, l='MpServer', x=128.97, y=70.50, z=1587.50], EntityPainting['Painting'/606, l='MpServer', x=128.00, y=70.00, z=1596.97], EntityPainting['Painting'/607, l='MpServer', x=128.97, y=70.00, z=1595.00], EntitySpark['Spark'/355, l='MpServer', x=36.50, y=69.50, z=1539.50], EntitySpark['Spark'/356, l='MpServer', x=37.50, y=69.50, z=1540.50], EntitySpark['Spark'/357, l='MpServer', x=37.50, y=69.50, z=1538.50], EntitySpark['Spark'/358, l='MpServer', x=38.50, y=69.50, z=1539.50], EntitySpark['Spark'/359, l='MpServer', x=40.50, y=69.50, z=1530.50], EntityArmorStand['Armor Stand'/360, l='MpServer', x=47.50, y=74.00, z=1558.50], EntityArmorStand['Armor Stand'/361, l='MpServer', x=46.50, y=74.00, z=1558.50], EntityCreeper['Creeper'/450167, l='MpServer', x=125.82, y=63.00, z=1484.58], BuilderEntityRenderForwarder['entity.mts_entity_renderer.name'/1922, l='MpServer', x=51.34, y=74.90, z=1560.86], EntityPainting['Painting'/648, l='MpServer', x=146.03, y=73.50, z=1608.50], EntityPainting['Painting'/649, l='MpServer', x=149.97, y=69.50, z=1575.50], EntityPainting['Painting'/650, l='MpServer', x=153.03, y=70.50, z=1573.50], EntityArmorStand['Armor Stand'/395, l='MpServer', x=52.50, y=74.00, z=1566.50], EntityPainting['Painting'/651, l='MpServer', x=157.03, y=69.50, z=1573.50], EntityArmorStand['Armor Stand'/396, l='MpServer', x=49.50, y=74.00, z=1552.50], EntityArmorStand['Armor Stand'/397, l='MpServer', x=49.50, y=74.00, z=1553.50], EntityArmorStand['Armor Stand'/398, l='MpServer', x=55.50, y=74.00, z=1565.50], EntityArmorStand['Armor Stand'/399, l='MpServer', x=49.50, y=74.00, z=1551.50], EntityArmorStand['Armor Stand'/400, l='MpServer', x=49.50, y=74.00, z=1550.50], EntityZombie['Zombie'/484775, l='MpServer', x=47.50, y=63.00, z=1505.50], EntityZombie['Zombie'/484774, l='MpServer', x=44.50, y=63.00, z=1501.50], EntityCustomNpc['Tanal'/430, l='MpServer', x=67.50, y=74.06, z=1564.50], EntitySpider['Spider'/484777, l='MpServer', x=32.99, y=63.00, z=1500.00], EntityCustomNpc['Raven'/431, l='MpServer', x=65.50, y=74.06, z=1565.50], EntityZombie['Zombie'/484776, l='MpServer', x=48.50, y=63.00, z=1508.50], EntityCustomNpc['Farcri'/432, l='MpServer', x=68.50, y=74.06, z=1552.50], EntityCreeper['Creeper'/461494, l='MpServer', x=22.50, y=63.00, z=1488.50], EntityZombie['Zombie'/448185, l='MpServer', x=21.50, y=63.00, z=1496.50], EntitySpider['Spider'/424404, l='MpServer', x=71.17, y=63.00, z=1490.93], EntityPlayerSP['IronSasquatch33'/220, l='MpServer', x=52.38, y=74.00, z=1560.50], EntityLatchedRenderer['unknown'/223, l='MpServer', x=8.50, y=65.00, z=8.50], BuilderEntityExisting['entity.mts_entity.name'/1503, l='MpServer', x=52.38, y=74.00, z=1560.50], EntitySpider['Spider'/468215, l='MpServer', x=62.50, y=63.00, z=1487.50], EntityZombie['Zombie'/468213, l='MpServer', x=56.50, y=63.00, z=1487.50], EntityPainting['Painting'/555, l='MpServer', x=125.50, y=69.50, z=1623.03], EntitySkeleton['Skeleton'/486643, l='MpServer', x=54.50, y=62.85, z=1489.50], EntitySpider['Spider'/486642, l='MpServer', x=54.50, y=63.00, z=1489.50], EntitySkeleton['Skeleton'/470001, l='MpServer', x=120.74, y=63.00, z=1484.46], EntitySpider['Spider'/464893, l='MpServer', x=104.79, y=63.00, z=1490.94], EntityCreeper['Creeper'/486648, l='MpServer', x=54.50, y=63.00, z=1482.50]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/223, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5653009544 bytes (5391 MB) / 13958643712 bytes (13312 MB) up to 13958643712 bytes (13312 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx13G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 63 mods loaded, 63 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version           | Source                                                    | Signature                                |
	|:------ |:------------------------ |:----------------- |:--------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                | 1.12.2            | minecraft.jar                                             | None                                     |
	| LCHIJA | mcp                      | 9.42              | minecraft.jar                                             | None                                     |
	| LCHIJA | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2859.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                    | 14.23.5.2859      | forge-1.12.2-14.23.5.2859.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ic2                      | 2.8.170-ex112     | industrialcraft-2-2.8.170-ex112.jar                       | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | advanced_solar_panels    | 4.3.0             | Advanced+Solar+Panels-4.3.0.jar                           | None                                     |
	| LCHIJA | codechickenlib           | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar             | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ancientwarfare           | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar                      | None                                     |
	| LCHIJA | redstoneflux             | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar                   | None                                     |
	| LCHIJA | ancientwarfareautomation | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar                      | None                                     |
	| LCHIJA | ancientwarfarenpc        | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar                      | None                                     |
	| LCHIJA | ancientwarfarestructure  | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar                      | None                                     |
	| LCHIJA | ancientwarfarevehicle    | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar                      | None                                     |
	| LCHIJA | antiqueatlas             | 4.6.3             | antiqueatlas-1.12.2-4.6.3.jar                             | None                                     |
	| LCHIJA | antiqueatlasoverlay      | 1.2               | antiqueatlas-1.12.2-4.6.3.jar                             | None                                     |
	| LCHIJA | appliedenergistics2      | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar                      | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | artemislib               | 1.0.6             | ArtemisLib-1.12.2-v1.0.6.jar                              | None                                     |
	| LCHIJA | baubles                  | 1.5.2             | Baubles-1.12-1.5.2.jar                                    | None                                     |
	| LCHIJA | jei                      | 4.16.1.301        | jei_1.12.2-4.16.1.301 3.jar                               | None                                     |
	| LCHIJA | botania                  | r1.10-363         | Botania+r1.10-363.jar                                     | None                                     |
	| LCHIJA | capsule                  | 1.12.2-3.4.76     | Capsule-1.12.2-3.4.76.jar                                 | None                                     |
	| LCHIJA | chickenchunks            | 2.4.2.74          | ChickenChunks-1.12.2-2.4.2.74-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | cofhcore                 | 4.6.6             | CoFHCore-1.12.2-4.6.6.1-universal.jar                     | None                                     |
	| LCHIJA | cofhworld                | 1.4.0             | CoFHWorld-1.12.2-1.4.0.1-universal.jar                    | None                                     |
	| LCHIJA | modcurrency              | 1.12-1.3.11       | Currency-1.12.0-1.3.11 (1).jar                            | None                                     |
	| LCHIJA | customnpcs               | 1.12              | CustomNPCs_1.12.2-(01Oct19).jar                           | None                                     |
	| LCHIJA | ebwizardry               | 4.3.7             | ElectroblobsWizardry-4.3.8.jar                            | None                                     |
	| LCHIJA | flansmod                 | 5.10.0            | Flan's+Mod-1.12.2-5.10.0.jar                              | None                                     |
	| LCHIJA | floocraftft              | 1.9.6             | Floocraft+1.12.2-1.9.6.jar                                | None                                     |
	| LCHIJA | ftblib                   | 5.4.7.2           | FTBLib-5.4.7.2.jar                                        | None                                     |
	| LCHIJA | ftbutilities             | 5.4.1.131         | FTBUtilities-5.4.1.131.jar                                | None                                     |
	| LCHIJA | ftbbackups               | 0.0.0.ftbbackups  | FTBUtilitiesBackups-1.0.0.5.jar                           | None                                     |
	| LCHIJA | craftablewizardry        | 2.0               | GIsCraftableWizardryItems-2.0.jar                         | None                                     |
	| LCHIJA | ichunutil                | 7.2.2             | iChunUtil-1.12.2-7.2.2.jar                                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | mts                      | 21.3.0            | Immersive+Vehicles-1.12.2-21.3.0.jar                      | None                                     |
	| LCHIJA | mtsseagullmilitarypack   | 1.4.0             | Immersive+Vehicles+(IV)+Seagull's+military+pack+1.7.4.jar | None                                     |
	| LCHIJA | mantle                   | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                                  | None                                     |
	| LCHIJA | tconstruct               | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                          | None                                     |
	| LCHIJA | thermalfoundation        | 2.6.7             | ThermalFoundation-1.12.2-2.6.7.1-universal.jar            | None                                     |
	| LCHIJA | immersiveengineering     | 0.12-92           | ImmersiveEngineering-0.12-92.jar                          | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | immersivepetroleum       | 1.1.10            | immersivepetroleum-1.12.2-1.1.10.jar                      | None                                     |
	| LCHIJA | immersivetech            | 1.3.10            | immersivetech-1.12-1.3.10.jar                             | None                                     |
	| LCHIJA | iv_timp                  | 1.0.0             | IV_Trin_Industrial_Machinery_Pack_1.0.3.jar               | None                                     |
	| LCHIJA | ivv                      | 1.5.0             | IV_Vanity-1.5.jar                                         | None                                     |
	| LCHIJA | journeymap               | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                               | None                                     |
	| LCHIJA | morph                    | 7.2.0             | Morph-1.12.2-7.2.1.jar                                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | harvestcraft             | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zg.jar                           | None                                     |
	| LCHIJA | patchouli                | 1.0-23.6          | Patchouli-1.0-23.6.jar                                    | None                                     |
	| LCHIJA | questionablyimmersive    | @VERSION@         | questionablyimmersive-1.12.2-0.1.0 1.jar                  | None                                     |
	| LCHIJA | tabula                   | 7.1.0             | Tabula-1.12.2-7.1.0.jar                                   | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | thermalexpansion         | 5.5.7             | ThermalExpansion-1.12.2-5.5.7.1-universal.jar             | None                                     |
	| LCHIJA | thermalcultivation       | 0.3.6             | ThermalCultivation-1.12.2-0.3.6.1-universal.jar           | None                                     |
	| LCHIJA | thermaldynamics          | 2.5.6             | ThermalDynamics-1.12.2-2.5.6.1-universal.jar              | None                                     |
	| LCHIJA | unuparts                 | 5.1.4             | UNU+Parts+Pack+[MTS]+1.12.2-21.3.0-5.1.4.jar              | None                                     |
	| LCHIJA | unucivil                 | 5.3.2             | UNU+Civilian+Pack+[MTS]+1.12.2-21.3.0-5.3.2.jar           | None                                     |
	| LCHIJA | unumilitary              | 5.0.0             | UNU+Military+Pack+[MTS]+1.12.2-21.3.0-5.0.0.jar           | None                                     |
	| LCHIJA | variedcommodities        | 1.12.2            | VariedCommodities_1.12.2-(13Jan22).jar                    | None                                     |
	| LCHIJA | wizardryfates            | 2.1.0             | WizardryFates-2.1.0.jar                                   | None                                     |
	| LCHIJA | zettaigrimoires          | 1.5.0             | ZettaiGrimoires-1.5.0.jar                                 | None                                     |
	| LCHIJA | zettaimagic              | 1.4.7             | ZettaiMagic-1.4.7.jar                                     | None                                     |
	| LCHIJA | ancientspellcraft        | 1.12.2-1.5.5      | AncientSpellcraft-1.12.2-1.5.5.jar                        | None                                     |
	| LCHIJA | wizardryutils            | 1.12.2-v1.1.1     | WizardryUtils-1.12.2-v1.1.1.jar                           | None                                     |
	| LCHIJA | morphspellpack           | 1.12.2-1.0.0      | MorphSpellPack-1.12.2-1.0.0.jar                           | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 30.0.101.1994' Renderer: 'Intel(R) UHD Graphics'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Patchouli open book context: n/a
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge-14.23.5.2859
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics GL version 4.6.0 - Build 30.0.101.1994, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz

### Expected behaviour

Spending large amounts of time in morph shouldn't cause an error of any kind.

### Steps to reproduce

1. become an animal of any kind
2. use any method to extend the time in morph for more then a few minutes
3. watch as the game crashes when you come out of morph

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

1.0.0

### Forge version

1.12.2 14.23.5.2859

### Other mods

crash log has a list

**Comment by wheel4598** [comment]
damn no fixes?
